encyclopedia/urls.py
from django.urls import path
from django.contrib import admin

import wiki

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path('', views.index, name="index"),
    path("wiki/<str:title>/", views.link_page, name="entries"),
    path("search_page/", views.search, name="search_query"),
    path("edit_page/<str:title>", views.edit_entry, name="edit"),
    path("new_page/", views.new_entry, name="new"),
    path("random/", views.random_entry, name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from fileinput import filename
from genericpath import exists
from multiprocessing import context
import random
from django.views.generic.base import TemplateView
from django import forms
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse

import markdown2


from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": SearchForm()
    })


def link_page(request, title):
    return render(request, "encyclopedia/info_page.html", {
        "title": title,
        "content": markdown2.markdown(util.get_entry(title))
    })


class SearchForm(forms.Form):
    query = forms.CharField(label='New Search', max_length=50)


def search(request):
    # populate the form
    form = SearchForm()
    # prepare for substring search with empty list for possible matches
    matches = []
    # check for GET request method and run request
    if request.method == "GET":
        form = SearchForm(request.GET)
        # check for valid input and clean up the data to query
        if form.is_valid():
            # loop through list of entries
            for entry in util.list_entries():
                # put query through a cleaned_data,
                # returns as string and makes all lowercase
                match_same = \
                    form.cleaned_data["query"].casefold() == entry.casefold()
                # if substring query matches anything,
                # clean entry as well
                substring_match = \
                    form.cleaned_data["query"].casefold() in entry.casefold()
                # query match shows user the matching page
                if match_same:
                    return HttpResponseRedirect(reverse("encyclopedia:entries",
                                                kwargs={"title": entry}))
                # shows list of possible matches
                elif substring_match:
                    matches.append(entry)
                    print(entry)
    context = {
        "form": SearchForm(),
        "substring_match": matches
    }
    response = render(request, "encyclopedia/search_page.html", context)
    return response


# setup for editing entries with textarea
class EntryForm(forms.Form):
    content = forms.CharField(
        required=True, widget=forms.Textarea, label="Edit Page Text")
# calling the request for HttpResponse and title to activate


def edit_entry(request, title):
    if request.method == 'POST':
        # saves the entry over the old md file
        util.save_entry(title, bytes(request.POST['content'], 'utf8'))
        # redirect to newly saved page
        return link_page(request, title)
    else:
        # show the original content
        title = title
        content = util.get_entry(title)
        form = EntryForm(request.GET or None, initial={'content': content})
        return render(request, "encyclopedia/edit_page.html", {
            "title": title,
            "content": content,
            "form": form
        })


# setup for new page creation
class New_Page(forms.Form):
    title = forms.CharField(
        required=True, widget=forms.TextInput, label="New Title")
    content = forms.CharField(
        required=True, widget=forms.Textarea, label="New Entry Text")
# function to start a new page with save_entry util


def new_entry(request):
    # request method should be post as this will add data
    if request.method == 'POST':
        form = New_Page(request.POST)
        # check if required entered data is valid
        if form.is_valid():
            # strips down title to compare against existing titles
            title = form.cleaned_data["title"].strip()
            content = form.cleaned_data["content"]
            # opens empty page to await new entry
            if util.get_entry(title):
                return render(request, "encyclopedia/new_page.html", {
                    "form": form,
                    "exists": True,
                    "title": title
                })
            else:
                form = form.cleaned_data["title"]
                util.save_entry(title, content)
                return link_page(request, title)
        else:
            return render(request, "encyclopedia/new_page.html", {
                "form": form,
                "exists": False
            })
    return render(request, "encyclopedia/new_page.html", {
        "form": New_Page(),
        "exists": False
    })


def random_entry(request):
    select_entry = util.list_entries()
    random_page = random.choice(select_entry)
    return redirect('encyclopedia:entries', title=random_page)

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}  
{% endblock %}

{% block body %}
    <h1> Edit {{ title }} Entry</h1>

    <form action="{% url 'encyclopedia:edit' title %}" method="post">
        {% csrf_token %}
        {{  form  }}
        <input type="submit" value="Save">
    </form>


{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
        <li><a href="{% url 'encyclopedia:entries' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/info_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}  
{% endblock %}

{% block body %}
    {{ content | safe }}

<div>
    <a href="{% url 'encyclopedia:edit' title %}">Edit Page</a>
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        <style>@import url('https://fonts.googleapis.com/css2?family=Quicksand&display=swap');</style>
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search_query' %}" method="get">
                    <input class="search" type="text" name="query" placeholder="Search Encyclopedia">               
                    <input type="submit">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}  
{% endblock %}

{% block body %}
  <h2>New Page</h2>
  <form action="{% url 'encyclopedia:new' %}" id="new-form"  method="post">
    {% csrf_token %}
    {{ form }}
    {% if exists %}
      <p class="alert alert-danger">Page {{ title }} already exists.</p>
    {% endif %}
    <input type="submit" class="button">
  </form>
{% endblock %}

encyclopedia/templates/encyclopedia/search_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}
{% if substring_match %}
        <h1>Search Results</h1>
            {% for query in substring_match %}
                <li><a href="{% url 'encyclopedia:search_query' %}"> {{ query }} </a></li>
                {% endfor %}
            {% else %}

        <h1>There's nothing here!</h1>
        {% endif %}

{% endblock %}